### ISSUE TITLE
THIS IS NOT AN ISSUE

### ISSUE THREAD

**Issue by colkat406** [Peilonrayz/Python_RPG_Game#2]
I'm sorry for doing this but I literally didn't know any other way to contact you but I was just wondering if you could check my code on stack exchange and if it was possible could you rewrite the parts that are wrong or need improving correctly please. I am asking you this because some one else posted something similar to what I posted you answered that question exceptionally well which shows that you really know python
It would be really helpful if you did this for me because this is an important project to me
https://codereview.stackexchange.com/q/208342/185468

Thanks

**Comment by Peilonrayz** [comment]
@colkat406 I've only started using GitHub again. Is this still something you'd like me to look at? If so post a new question and I'll see if I can have a go.

Also this goes against Stack Exchange rules AFAIK. I recommend that you don't do it again :)
